name: Apply Terraform to Civo

on:
  push:
    branches:
      - main
    paths:
      - 'infra/tf/**'

env:
  civo_token: ${{ secrets.civo_token }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0 # Specify the Terraform version you're using

    - name: Terraform Init
      id: init
      run: terraform init infra/tf/

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=tfplan infra/tf/
      continue-on-error: true

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan